// Exact public reel destinations checked in a signed-out browser, September 2026.
// Covers are existing portfolio photos, not extracted frames from the reels.
export const films = [
  {
    id: "xolvit-one",
    title: "A challenge opened a door.",
    category: "Conversations",
    setting: "XOLVIT / VTAC",
    creator: "@xolvit",
    date: "November 2025",
    duration: "1:27",
    description:
      "Part one of my Xolvit interview: the VTAC challenge and the connection that led to an internship.",
    url: "https://www.instagram.com/xolvit/reel/DQ3J-MFgBhm/",
    cover: "/images/journey-5-0.webp",
    coverAlt: "Mun Wai’s Xolvit experience, from his photo journal",
    coverNote: "Photo journal / Xolvit",
  },
  {
    id: "xolvit-two",
    title: "What the internship taught me.",
    category: "Conversations",
    setting: "XOLVIT / VTAC",
    creator: "@xolvit",
    date: "November 2025",
    duration: "2:23",
    description:
      "Part two: reflecting on the internship, what I learnt along the way and where those experiences could lead.",
    url: "https://www.instagram.com/xolvit/reel/DRN1Gh0kw3z/",
    cover: "/images/journey-12-0.webp",
    coverAlt: "Mun Wai’s VTAC experience, from his photo journal",
    coverNote: "Photo journal / VTAC",
  },
  {
    id: "monash-podcast",
    title: "Psychology meets AI.",
    category: "Conversations",
    setting: "MONASH DEEPNEURON / AI UNPLUGGED",
    creator: "@monashdeepneuron · @aiunplugged_mdn",
    date: "October 2025",
    duration: "0:07",
    description:
      "The short announcement for my AI Unplugged appearance. The full conversation is in the listening room above.",
    url: "https://www.instagram.com/monashdeepneuron/reel/DQLidsijP1c/",
    lettering: ["AI", "UNPLUGGED"],
  },
  {
    id: "uni-first-year",
    playback: "instagram",
    title: "The first year, and the people.",
    category: "University life",
    setting: "MELBOURNE / FIRST YEAR",
    creator: "@munwai111",
    date: "January 2023",
    duration: "2:01",
    description:
      "My first year at university: new friendships, academic curiosity and the everyday moments that made it mine.",
    url: "https://www.instagram.com/munwai111/reel/Cm6SOU6hQrn/",
    cover: "/images/journey-4-0.webp",
    coverAlt:
      "Activities and volunteering at RMIT, from Mun Wai’s photo journal",
    coverNote: "Photo journal / RMIT life",
  },
  {
    id: "kansai",
    title: "One last day in Kansai.",
    category: "University life",
    setting: "JAPAN / WINTER SCHOOL",
    creator: "@munwai111",
    date: "March 2023",
    duration: "6:06",
    description:
      "Finishing Winter School at Kansai University, with the teamwork and friendships that came with it.",
    url: "https://www.instagram.com/munwai111/reel/Cphit4iuxcS/",
    cover: "/images/journey-7-0.webp",
    coverAlt: "Kansai University exchange, from Mun Wai’s photo journal",
    coverNote: "Photo journal / Kansai",
  },
  {
    id: "mount-gambier",
    title: "The road to Mount Gambier.",
    category: "Out & about",
    setting: "SOUTH AUSTRALIA / WITH FRIENDS",
    creator: "@antomi_and_go",
    date: "June 2025",
    duration: "0:43",
    description:
      "A road trip with friends, shared by @antomi_and_go. A little of the life between the work.",
    url: "https://www.instagram.com/antomi_and_go/reel/DLQyqoih-4V/",
    lettering: ["MOUNT", "GAMBIER"],
  },
  {
    id: "japan-street",
    playback: "instagram",
    title: "A little wander through Japan.",
    category: "Out & about",
    setting: "JAPAN / JULY 2024",
    creator: "@munwai111",
    date: "July 2024",
    duration: "0:14",
    description:
      "A short walk along a Japanese shopping street. One of the small moments I wanted to keep.",
    url: "https://www.instagram.com/munwai111/reel/C99isrBtuAq/",
    lettering: ["A LITTLE", "WANDER."],
  },
  {
    id: "mount-buffalo",
    playback: "instagram",
    title: "A day out at Mount Buffalo.",
    category: "Out & about",
    setting: "VICTORIA / WITH FRIENDS",
    creator: "@munwai111",
    date: "April 2026",
    duration: "1:35",
    description:
      "A trip to Mount Buffalo with friends, through the moments I caught on camera.",
    url: "https://www.instagram.com/reel/DW8JkAJDXAZ/",
    lettering: ["MOUNT", "BUFFALO"],
  },
  {
    id: "twenty-four",
    playback: "instagram",
    title: "2024, this too shall pass.",
    category: "University life",
    setting: "JAPAN / MELBOURNE / GRADUATION",
    creator: "@munwai111",
    date: "January 2025",
    duration: "12:54",
    description:
      "My longer film looking back on 2024: travels in Japan, time with friends and graduation at RMIT.",
    url: "https://www.instagram.com/munwai111/reel/DEb5iJtTShe/",
    cover: "/images/journey-10-0.webp",
    coverAlt: "Mun Wai’s RMIT graduation, from his photo journal",
    coverNote: "Photo journal / Graduation",
  },
];
